### ISSUE TITLE
Invalid remote: origin

### ISSUE THREAD

**Issue by tuxick** [zeapo/Android-Password-Store#238]
when trying to clone i now get:

Internal exception occurred:

Message from jgit:
Invalid remote: origin

When i deliberately enter wrong password it returns auth failed, so it does try to connect.

**Comment by zeapo** [comment]
That means that the path you gave it is not a git repository

**Comment by tuxick** [comment]
it's the same path my linux clients use, but maybe the problem is i use a different port, so it's "user@host.example.com:1234/git/pass"

**Comment by zeapo** [comment]
Is `git` in your home directory or at the root?

**Comment by tuxick** [comment]
in home directory

**Comment by zeapo** [comment]
try `user@host.example.com:1234/home/user/git/pass`

**Comment by tuxick** [comment]
\o/ that works, thanks! but i think it's a bit unclear, at least i'm not used to having to pass complete path :)

**Comment by zeapo** [comment]
Because when using a custom port you precede the path by a `/` which is the root, hence you have to give an absolute path. That's a minor issue with custom ports. 
You can use `user@host.example.com:1234/~/git/pass` if you do not want to specify the full absolute path.

**Comment by tuxick** [comment]
oh well, it finally works for me now that #122 has been fixed :)

**Comment by jfjallid** [comment]
Is the fix uploaded to the Android Play Store? I'm still experiencing this problem.

**Comment by zeapo** [comment]
Actually this is a non-issue. Did you apply the suggestion in my previous comment?

**Comment by jfjallid** [comment]
I'm not sure how to apply your suggestion in my case. I'm cloning the repo from another user's home directory on a custom port so my command is like this:
user1@example.com:1234/home/user2/.password-store/

User1 has the correct permission to access the files from user2. It worked before but I recreated the git repo and tried to sync again when it started to complain.

**Comment by zeapo** [comment]
Oh, you can't clone from `.password-store`, this is a non-bare repository. As mentioned in the FAQ:
**Q**: What kind of repository can I clone from?
**A**: Make sure to only clone from bare repositories (see [git-clone(1)](https://git-scm.com/docs/git-clone) for how to create a bare repository from an existing one). Otherwise the clone will fail.

**Comment by jfjallid** [comment]
Okey I missed that one. Was just confused because I successfully cloned from the password store repo before.
