### ISSUE TITLE
[BUG]Can not create passwords

### ISSUE THREAD

**Issue by Schueni1** [zeapo/Android-Password-Store#955]
When I try to create a new password I get the following error message 
`Error from OpenKeyChain : Attempt to get length of null array`

1. Install App Version 1.10.0
2. Try to create a new password

I'm also not able to select a gpg key from OpenKeyChain anymore. 
The option in the settings menu is missing.
In case it is relevant. I'm using a Curve25519 gpg key to encrypt my passwords.

 - Device: OnePlus 7T Pro
 - OS: Android 10
 - App Version 1.10.0

**Comment by msfjarvis** [comment]
Can you tell us the contents of your `.gpg-id` file?

**Comment by Schueni1** [comment]
I have two ```.gpg-id``` files because I encrypt the passwords in one folder with a different key.
Do you need both?

**Comment by joshcangit** [comment]
I also have this problem but I got a different error message.

```
Found .gpg-id, but it did not contain a key ID, fingerprint or user ID
```

This was after I updated and edited exist entries. No changes could be saved.

- Android version:
10
- Device manufacturer:
samsung
- Device model:
SM-G973F
- App version:
1.10.0

**Comment by msfjarvis** [comment]
> I have two `.gpg-id` files because I encrypt the passwords in one folder with a different key.
> Do you need both?

If you can provide both, it'd certainly be very helpful.



> I also have this problem but I got a different error message.
> 
> ```
> Found .gpg-id, but it did not contain a key ID, fingerprint or user ID
> ```

Yours too, please :)

**Comment by joshcangit** [comment]
I couldn't access the one in the hidden repository but for the external repository, that file was empty.

Created a new external repository and the .gpg-id file is also empty.

**Comment by msfjarvis** [comment]
> I couldn't access the one in the hidden repository but for the external repository, that file was empty.
> 
> Created a new external repository and the .gpg-id file is also empty.

Sigh, this is the exact problem I was hoping to not face. We don't ask users to select a GPG key during repo initialization so the `.gpg-id` file stays empty. The app's support for generating stores on-device is particularly kludgy and a source of pain over the years. If you use the store on a computer with a `pass` client I'd recommend initializing it there then copying it over to the phone as a workaround for now.

**Comment by msfjarvis** [comment]
I think the 'correct' ~~workaround~~ fix here would be to bring back the key selection activity and wire it into the repository creation flow to write a key into `.gpg-id`. For existing repositories, I think I can wire in a fallback for empty `.gpg-id` files. What do you think @FabianHenneke?

**Comment by Schueni1** [comment]
Content of the root .gpg-id:
```85364A44A39EBE8CF50F41124F6C4940B6273A22```
The special folder gpg-id:
```CE85A9D522FECB4484ED11C3D4EF0667780D7BA1```
Both keys are curve25519.

**Comment by fmeum** [comment]
> I think the 'correct' ~workaround~ fix here would be to bring back the key selection activity and wire it into the repository creation flow to write a key into `.gpg-id`. For existing repositories, I think I can wire in a fallback for empty `.gpg-id` files. What do you think @FabianHenneke?

@msfjarvis This sounds reasonable, but could probably be combined into a single flow: Whenever the `.gpg-id` file is empty and a password should be encrypted, the user would be asked to select a key and that key's ID would then be stored in the file.

**Comment by msfjarvis** [comment]
> > I think the 'correct' ~workaround~ fix here would be to bring back the key selection activity and wire it into the repository creation flow to write a key into `.gpg-id`. For existing repositories, I think I can wire in a fallback for empty `.gpg-id` files. What do you think @FabianHenneke?
> 
> @msfjarvis This sounds reasonable, but could probably be combined into a single flow: Whenever the `.gpg-id` file is empty and a password should be encrypted, the user would be asked to select a key and that key's ID would then be stored in the file.

That makes sense and is easier as well, gonna do that. Can you look into why @Schueni1's keys fail?

**Comment by fmeum** [comment]
> That makes sense and is easier as well, gonna do that. Can you look into why @Schueni1's keys fail?

On it, am setting up a repo to reproduce.

**Comment by fmeum** [comment]
We have a test repo now: https://github.com/android-password-store/pass-test

**Comment by fmeum** [comment]
@msfjarvis  I can reproduce @Schueni1's issue as well as a different issue with long key IDs.

**Comment by msfjarvis** [comment]
> @msfjarvis I can reproduce @Schueni1's issue as well as a different issue with long key IDs.

Great. I'm nearly done with the key selection as well.

**Comment by fmeum** [comment]
@msfjarvis The issue specific to long key IDs should be fixed by #959, the one that @Schueni1 is affected by lies deeper. Will need some more time, but I have an idea.

**Comment by msfjarvis** [comment]
> @msfjarvis The issue specific to long key IDs should be fixed by #959, the one that @Schueni1 is affected by lies deeper. Will need some more time, but I have an idea.

Yeah, the crash I faced with my PR is fixed but now I'm hitting the same bug.

**Comment by fmeum** [comment]
@Schueni1's bug should be fixed by #960.

**Comment by msfjarvis** [comment]
And with that merged into #958 I'm prompted to select a key when my `.gpg-id` file is empty and am subsequently able to encrypt the password. The semantics around how we create the commits is a bit fuzzy right now but things work and we can ship this into 1.10.1 tonight.

**Comment by lekv** [comment]
I'm still getting this error with version **1.10.1**:
```
Found .gpg-id, but it did not contain a key ID, fingerprint or user ID
```

My .gpg-id has a single line with the 8 character, uppercase key id ending in a newline. This must have stopped working recently, but I verified on a check-out repo that the .gpg-id file has not changed. I also tried checking out the repo again and deleted and re-added the key to OpenKeyChain where it looks all good to me.

Am I missing any steps to fix this?

**Comment by fmeum** [comment]
> I'm still getting this error with version **1.10.1**:
> ```
> Found .gpg-id, but it did not contain a key ID, fingerprint or user ID
> ```
> 
> My .gpg-id has a single line with the 8 character, uppercase key id ending in a newline. This must have stopped working recently, but I verified on a check-out repo that the .gpg-id file has not changed. I also tried checking out the repo again and deleted and re-added the key to OpenKeyChain where it looks all good to me.
> 
> Am I missing any steps to fix this?

8 character key IDs are not supported as identifiers by OpenKeychain as the API requires us to provide the last 8 bytes (16 characters) of the fingerprint. Previously, we were not using the `.gpg-id` file at all and relied on manual key selection instead, which is why this broke for you now.

The best and only fix I see right now would be to change the contents of your `.gpg-id` to the fingerprint or long ID of your key, both of which are supported. If you potentially add untrusted keys to OpenKeychain, I would definitely recommend to go for the full fingerprint in order to prevent collision attacks.

**Comment by lekv** [comment]
That was it, thanks for the fast reply! After I put the full ID into the `.gpg-id` file, things worked as expected. I had originally created the file using the `pass` command line utility and hadn't changed it since 2016. Maybe we should have a better warning or include a link to some FAQ entry if this is likely going to affect a lot of users.

**Comment by fmeum** [comment]
> That was it, thanks for the fast reply! After I put the full ID into the `.gpg-id` file, things worked as expected. I had originally created the file using the `pass` command line utility and hadn't changed it since 2016. Maybe we should have a better warning or include a link to some FAQ entry if this is likely going to affect a lot of users.

Thanks for the suggestion, I'm adding a warning in #974.

**Comment by lekv** [comment]
Awesome! Left a comment there. Thanks again for the great work and quick help!

**Comment by FloatingLizard** [comment]
Hello,
  I just installed Version 1.11.3 and I am unable to create a password and the error is .gpg-id is too short, please use a long ID.
Is there an update as this one that was updated 3 weeks ago according to the F-droid store.  Or do I have to edit the .gpg-id ? 

Thanks

**Comment by msfjarvis** [comment]
> Hello,
> I just installed Version 1.11.3 and I am unable to create a password and the error is .gpg-id is too short, please use a long ID.
> Is there an update as this one that was updated 3 weeks ago according to the F-droid store.
> 
> Thanks

There's no update to be made for this, you'll need to fix your store. `gpg --list-keys` on your computer will give you the full key IDs that need to be in your `.gpg-id` file. v1.12.0 has been added to F-Droid [a week ago](https://gitlab.com/fdroid/fdroiddata/-/commit/7a025580453d52bca138fbc96a5c0c56e138dd0a) so you should update your repository.

**Comment by tomasi-o** [comment]
I am using Password Store 1.13. Upon trying to create a new password entry I am getting the error message
`Failed to locate .gpg-id, is your store set up correctly?` So I am guessing this belongs to this issue. I can output my full key ID via `gpg --list-keys`, but where do I put it? 
Curiously I am able to create password entries inside a newly made folder, but not in an old one or in the root of the app.
Thank you in advance for your help.

**Comment by msfjarvis** [comment]
> I am using Password Store 1.13. Upon trying to create a new password entry I am getting the error message
> `Failed to locate .gpg-id, is your store set up correctly?` So I am guessing this belongs to this issue. I can output my full key ID via `gpg --list-keys`, but where do I put it?
> Curiously I am able to create password entries inside a newly made folder, but not in an old one or in the root of the app.
> Thank you in advance for your help.

On a computer, create `.gpg-id` in the root of the store and add your long key ID as the file's contents.

**Comment by tomasi-o** [comment]
How can I create sth. in the root of the store on a computer? Is the store not some folder on my android phone? Sorry, I am rather new to this.

**Comment by msfjarvis** [comment]
> How can I create sth. in the root of the store on a computer? Is the store not some folder on my android phone? Sorry, I am rather new to this.

If you're only using the app then I'm not really sure how you managed to reach this state. Please join the Gitter chatroom to avoid spamming this issue since your problem is unrelated to this: https://gitter.im/android-password-store/public

**Comment by tomasi-o** [comment]
ok, done - thx for your quick response.
